--- 
content_type: html
title: Cube Drone - Environment Management
categories: ["Cube Drone", "Tech"]
visible: true
created: "2012-12-02T22:40:48-07:00"
content: "<iframe width=\"640\" height=\"480\" src=\"http://www.youtube.com/embed/bC5djYeF1dk\" frameborder=\"0\" allowfullscreen></iframe><br/> 

A short lecture on Environment Management. 
"
